export const customStyles = {
	fontFamily:  'Helvetica, sans-serif',
	gradientStart:  '#005792',
	gradientMid:  '#005792',
	gradientEnd:  '#005792',
	locationFontColor:  '#FFF',
	todayTempFontColor:  '#FFF',
	todayDateFontColor:  '#B5DEF4',
	todayRangeFontColor:  '#B5DEF4',
	todayDescFontColor:  '#B5DEF4',
	todayInfoFontColor:  '#B5DEF4',
	todayIconColor:  '#FFF',
	forecastBackgroundColor:  '#005792',
	forecastSeparatorColor:  '#DDD',
	forecastDateColor:  '#DDD',
	forecastDescColor:  '#DDD',
	forecastRangeColor:  '#DDD',
	forecastIconColor:  '#4BC4F7',
};